{% set version = "1.2.3" %}

package:
  name: tuiview
  version: {{ version }}

source:
  fn: TuiView-{{ version }}.tar.gz
  url: https://bitbucket.org/chchrsc/tuiview/downloads/TuiView-{{ version }}.tar.gz
  sha256: 6c63ae83a7e845b5f96316cdb7d7007e1c74158e47e2a75d8dcc5a22e24e1c31

build:
  number: 1
  entry_points:
    - tuiview = tuiview.viewerapplication:run
    - tuiviewwritetable = tuiview.writetableapplication:run

requirements:
  build:
    - python
    - numpy 1.8.*  # [not (win and (py35 or py36))]
    - numpy 1.9.*  # [win and py35]
    - numpy 1.11.*  # [win and py36]    
    - gdal 2.2.*
    - pyqt 5.6.*
  run:
    - python
    - numpy >=1.8  # [not (win and (py35 or py36))]
    - numpy >=1.9  # [win and py35]
    - numpy >=1.11  # [win and py36]    
    - gdal 2.2.*
    - pyqt 5.6.*

test:
  imports:
    - tuiview
    # make sure we can import the C extension
    - tuiview.vectorrasterizer
  commands:
    - tuiviewwritetable -h
    - conda inspect linkages -p $PREFIX tuiview  # [not win]
    - conda inspect objects -p $PREFIX tuiview  # [osx]

about:
  home: http://tuiview.org/
  license: GPL-2.0
  license_file: LICENSE.txt
  summary: Simple raster viewer. Supports Geolinked Windows, Raster Attribute Querying and Editing and Geographic Selection, Vector Overlay, Flicker, Profile Tool.

extra:
  recipe-maintainers:
    - gillins
    - danclewley
