{% set version = "1.2.1" %}

package:
  name: tuiview
  version: {{ version }}

source:
  fn: TuiView-{{ version }}.tar.gz
  url: https://bitbucket.org/chchrsc/tuiview/downloads/TuiView-{{ version }}.tar.gz
  sha256: 5c39c37aaf2b4e0e9a0a57c3a4ec3b27c4139134384a15b8c5831c2ecf3394bf

build:
  number: 0
  entry_points:
    - tuiview = tuiview.viewerapplication:run
    - tuiviewwritetable = tuiview.writetableapplication:run

requirements:
  build:
    - python
    - numpy 1.7.*  # [py27]
    - numpy 1.9.*  # [py35]
    - numpy 1.11.*  # [py36]
    - gdal 2.1.*
    - pyqt 5.6.*
  run:
    - python
    - numpy >=1.7  # [py27]
    - numpy >=1.9  # [py35]
    - numpy >=1.11  # [py36]
    - gdal 2.1.*
    - pyqt 5.6.*

test:
  imports:
    - tuiview
  commands:
    - tuiviewwritetable -h
    - conda inspect linkages -p $PREFIX tuiview  # [not win]
    - conda inspect objects -p $PREFIX tuiview  # [osx]

about:
  home: http://tuiview.org/
  license: GPL-2.0
  license_file: LICENSE.txt
  summary: Simple raster viewer. Supports Geolinked Windows, Raster Attribute Querying and Editing and Geographic Selection, Vector Overlay, Flicker, Profile Tool.

extra:
  recipe-maintainers:
    - gillins
    - danclewley
