{% set version = "1.1.11" %}


package:
    name: tuiview
    version: {{ version }}

source:
    fn: TuiView-{{ version }}.tar.gz
    url: https://bitbucket.org/chchrsc/tuiview/downloads/TuiView-{{ version }}.tar.gz
    sha256: 4657ec81466d2ca4bfa55792941afd46de26f34f5cc46b3b58b8949413f0b3c2

build:
    number: 1
    entry_points:
        - tuiview = tuiview.viewerapplication:run
        - tuiviewwritetable = tuiview.writetableapplication:run

requirements:
    build:
        - python
        - numpy x.x
        - gdal 2.2.*
        - pyqt 4.11.*
    run:
        - python
        - numpy x.x
        - gdal 2.2.*
        - pyqt 4.11.*

test:
    imports:
        - tuiview

about:
    home: http://tuiview.org/
    license: GPLv2
    summary: Simple raster viewer. Supports Geolinked Windows, Raster Attribute Querying and Editing and Geographic Selection, Vector Overlay, Flicker, Profile Tool. 

extra:
    recipe-maintainers:
        - gillins
        - danclewley
