travis:
  secure:
    BINSTAR_TOKEN: Rrwrgv/seC+inCP98oyo13wAraEufVFt+MM4i7s2pmj4Hm8+UT3/8mZWx8ip5ulo3x5x2Kgx0+4+NAU3HUBXmlgw5n7U8jFdS32DTcirZ1pLYj6gV2W2A4LwfeeVno236ik7MejfMvlwOELKvozjOnPl08UAPY8ey7GszTVuAkL+mgztVEuiMHirx60OM/k8Da94ZPb5DqJuRD+MPlLvqePsFLWbHHNbyMeWN3jbi6RcvWh3QViquvhRd/h07NpJCPNE0JF/quq0byRSIe6SWvwirTIvVM/ExPrPArxqg+PU1Aq5xqjH1Rlb1Lb2XBmLIjMB33N/g6Vgj/DuISX5T/eQcvac3R2Zkb6oVVFQi9jNT3TmaGM5fkhKowW7WYe0ppCN2AG5eKMIckqY+eKQiTzHFzvGZRIDzm37hMKdksrtVw7lGzey9wqQs/QyHOPsHgZsbbYGPIQfCeETS4x8PHSYg5RRJ/TfaDAa33f69Zl1kg+P2mBF0euzkOVj64q1StYUQ2T3J2+GYe+ErvDlh+pwI7pZ714UfAHupk0ESFaCwvHLSUMmGdYoT/kwy1glaMZMZs+pv5CUxjqNZbO4lIXql+NGNJEKsbtVuKBclPMlyNmxPLYkPwh7rU605GmbMlH+Omze4H5kL5JEXi2E1OzszDp4vSRI/AucEAB+QDk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
